// Code generated by "stringer -type AckTypeIn acktype.go"; DO NOT EDIT.

package mysensors

import "strconv"

const _AckTypeIn_name = "NORMACK"

var _AckTypeIn_index = [...]uint8{0, 4, 7}

func (i AckTypeIn) String() string {
	if i < 0 || i >= AckTypeIn(len(_AckTypeIn_index)-1) {
		return "AckTypeIn(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AckTypeIn_name[_AckTypeIn_index[i]:_AckTypeIn_index[i+1]]
}
