// Code generated by "stringer -type AckTypeOut acktype.go"; DO NOT EDIT.

package mysensors

import "strconv"

const _AckTypeOut_name = "UNACKREQACK"

var _AckTypeOut_index = [...]uint8{0, 5, 11}

func (i AckTypeOut) String() string {
	if i < 0 || i >= AckTypeOut(len(_AckTypeOut_index)-1) {
		return "AckTypeOut(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AckTypeOut_name[_AckTypeOut_index[i]:_AckTypeOut_index[i+1]]
}
