// Code generated by "stringer -type CommandType commandtype.go"; DO NOT EDIT.

package mysensors

import "strconv"

const _CommandType_name = "PresentationSetReqInternalStreamUnknownCommandType"

var _CommandType_index = [...]uint8{0, 12, 15, 18, 26, 32, 50}

func (i CommandType) String() string {
	if i < 0 || i >= CommandType(len(_CommandType_index)-1) {
		return "CommandType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommandType_name[_CommandType_index[i]:_CommandType_index[i+1]]
}
