// Code generated by "stringer -type Node node.go"; DO NOT EDIT.

package mysensors

import "strconv"

const (
	_Node_name_0 = "unknownwxm"
	_Node_name_1 = "fam"
	_Node_name_2 = "gar"
	_Node_name_3 = "bob"
	_Node_name_4 = "hvac"
)

var (
	_Node_index_0 = [...]uint8{0, 7, 10}
)

func (i Node) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _Node_name_0[_Node_index_0[i]:_Node_index_0[i+1]]
	case i == 20:
		return _Node_name_1
	case i == 30:
		return _Node_name_2
	case i == 50:
		return _Node_name_3
	case i == 90:
		return _Node_name_4
	default:
		return "Node(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
