// Code generated by "stringer -type StreamType streamtype.go"; DO NOT EDIT.

package mysensors

import "strconv"

const _StreamType_name = "ST_FIRMWARE_CONFIG_REQUESTST_FIRMWARE_CONFIG_RESPONSEST_FIRMWARE_REQUESTST_FIRMWARE_RESPONSEST_SOUNDST_IMAGE"

var _StreamType_index = [...]uint8{0, 26, 53, 72, 92, 100, 108}

func (i StreamType) String() string {
	if i < 0 || i >= StreamType(len(_StreamType_index)-1) {
		return "StreamType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StreamType_name[_StreamType_index[i]:_StreamType_index[i+1]]
}
